[package]
name = "server"
version = "0.1.0"
authors = ["K0R0VA <yarykov.m@edu.narfu.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-web = "3.0"
actix-web-actors = "3.0.0"
diesel = { version = "1.4.5", features = ["postgres", "uuid","r2d2", "chrono"] }
chrono = {version = "0.4.6", features = ["serde"]}
serde_derive = "1.0.116"
serde_json = "1.0.57"
serde =  "1.0"
r2d2 = "0.8.9"
uuid = {version = "0.6", features = ["serde", "v4"] }
dotenv = "0.15.0"
failure = "0.1.8"
futures = "0.3.5"

